- .specific/_qs_deploy_links.adoc
- .specific/_settings.adoc
- .specific/architecture.adoc
- .specific/faq_troubleshooting.adoc
- .specific/troubleshooting.adoc
- _layout_cfn.adoc
- cost.adoc
- deployment_steps.adoc
> Updating doc content

- .specific/_qs_deploy_links.adoc
- .specific/architecture.adoc
- deployment_steps.adoc
Update to image displays
Launch links open in new window
> Image & link updates

- .css/quickstart.css
- .specific/service_limits.adoc
Make pretty & adjusting for table headers in service limits
> CSS updates

- .css/quickstart.css
> Updating H colors & content width

- .specific/_settings.adoc
- .specific/pre-reqs.adoc
- introduction.adoc
> hew heading

- _layout_cfn.adoc
- cost.adoc
- planning_deployment.adoc
Tweaked files to meet writing standards.
> Edited boilerplate topics

- .specific/overview_target_and_usage.adoc
- introduction.adoc
- overview.adoc
- Adding logo
- Updating overview
> Logo and Overview

- introduction.adoc
Updating to pull from '/docs/boilerplate/.images/'
> Updating logo location

- overview.adoc
Updated "note" about sharing information with partners. Deleted "please" to meet style guidelines. 
> Update overview.adoc with modified note about sharing information 

- .css/quickstart.css
- .specific/faq_troubleshooting.adoc
- deployment_steps.adoc
- planning_deployment.adoc
https://github.com/aws-quickstart/quickstart-documentation-base-common/issues/31
https://github.com/aws-quickstart/quickstart-documentation-base-common/issues/34
https://github.com/aws-quickstart/quickstart-documentation-base-common/issues/36
https://github.com/aws-quickstart/quickstart-documentation-base-common/issues/38
> Fixes the following issues:

- .css/quickstart.css
- _layout_cfn.adoc
- deployment_steps.adoc
- introduction.adoc
- overview.adoc
- planning_deployment.adoc
Changes for helping to generate headings and make edited content clearer.
> Preview change

- .css/quickstart.css
- disclaimer.adoc
- index-docinfo-footer.html
- index.adoc
Adding privacy and site terms into the footer, as per AWS compliance guidelines.
> Add privacy and site terms in footer

- introduction.adoc
*Description of changes:* Correcting commenting
> Correcting commenting

- CODEOWNERS
does what it says on the label
> content team should be asked for review of pr's with changes to adoc files

- .specific/_settings.adoc
- .specific/architecture.adoc
- .specific/deploy_steps.adoc
- .specific/deployment_options.adoc
- .specific/overview_target_and_usage.adoc
- planning_deployment.adoc
> Small edits in multiple docs

- .specific/architecture.adoc
- .specific/faq_troubleshooting.adoc
- .specific/regions.adoc
- _layout_cfn.adoc
> A few small edits

- .specific/deploy_steps.adoc
- .specific/service_limits.adoc
- deployment_steps.adoc
- planning_deployment.adoc
> Couple of small edits

- .specific/deploy_steps.adoc
- .specific/faq_troubleshooting.adoc
- .specific/specialized_knowledge.adoc
- deployment_steps.adoc
- planning_deployment.adoc
> Couple of edits

- _layout_cfn_eks_module.adoc
- deployment_steps_eks_module.adoc
- planning_deployment.adoc
- planning_deployment_eks_module.adoc
Various text updates to align closer with style guidelines.
> Pr for eks boilerplate

- .specific/faq_troubleshooting.adoc
- planning_deployment.adoc
Edited per AWS style + clarified comments.
> Updated a couple of docs

- .utils/create_repo_structure.sh
> Reverted PR #108

- .specific/deploy_steps.adoc
- .specific/licenses.adoc
> Clarifications to two files

- index-docinfo-footer.html
> Copyright: 2021

- deployment_steps_eks_module.adoc
> Addressed Jay's //TODO question

- cost.adoc
The word "paid" adds no value since we're already talking about costs.
> Removed "paid"

- .specific/_settings.adoc
- introduction.adoc
> Added a byline attribute for aws-contributors

- .utils/generate_dynamic_content.sh
> Adjust to cater for set -e

- deployment_steps.adoc
Reverts aws-quickstart/quickstart-documentation-base-common#131
> Revert "Update deployment_steps.adoc"

- .specific/_settings.adoc
- introduction.adoc
> Added a new byline attribute: "other-contributors"

- _layout_cfn_cdk_module.adoc
> Adding deployment options back in for CDK

- .specific/_settings.adoc
- _layout_cfn.adoc
- deploy_control_tower.adoc
> Adding Control Tower boilerplate file

- _layout_cfn.adoc
- _layout_cfn.lang.adoc
- _layout_cfn_eks_module.adoc
Added Patching Statement for all doc types
> add Patching statement for all doc types

- .utils/docs_built_in_codebuild.sh
> Adding s3 upload excludes to cut down on unnecessary s3 objects

- .specific/_settings.adoc
> Changed team name (Quick Start > I&A) in byline

- _layout_cfn_cdk_module.adoc
- deployment_steps_cdk_module.adoc
> Fixing issue with CDK deployment

- .specific/_settings.adoc
- .specific/architecture.adoc
- .specific/deploy_steps.adoc
- _layout_cfn.adoc
- _layout_cfn.lang.adoc
- _layout_cfn_cdk_module.adoc
- deployment_steps.adoc
- planning_deployment.adoc
- planning_deployment.lang.adoc
> Minor revisions to text and links

- .specific/.cdk/deploy_steps.adoc
> Updated for new region setup

- .utils/generate_parameter_tables.py
> fixing formatting of parameters with asterisk and pipe

- .utils/generate_parameter_tables.py
document generation fails when the parameter is number. because it won't be iterable
converted to string 
> fixing issue with parameter value being number not iterable
