aws-quickstart/quickstart-documentation-base-common

deployment_steps.adoc

cfn_outputs image is not linked via anchor tag, instead hardcoded.
Fixed hardcoded reference to cfn_outputs image

Fix hardcoded reference to cfn_outputs image

---

.specific/deploy_steps.adoc

In the deployment guides we usually include a template download link by the parameter tables.
This is added to be in the same table as the launch links.

Adding in links for templates

---

.utils/generate_parameter_tables.py

*Issue #, if available:* 
12
I added the option to accept an "Order" attribute from the template metadata. If the attribute is present it is used as the sorting basis for the entrypoints. The entrypoint creation will be based on the values of the Order attribute, this value is converted to a string prior to sorting. The script will output to the console the index value and entrypoint name in the order that they will appear in the documentation.
i.e.
- Index - a - Launch into a new VPC
- Index - b - Launch into an existing VPC

Added support for ordering entrypoints

---

introduction.adoc

Quick Start icon in the deployment guide should come from aws-quickstart bucket

Quick Start icon in the deployment guide should come from aws-quickstart bucket

---

.specific/_settings.adoc
planning_deployment.adoc

Acrolinx says to avoid using the word "action" when referring to an AWS operation. Vinod confirms that it makes sense to remove the word here.

Small updates to boilerplate docs

---

.utils/commit_and_push_to_ghpages.sh

Github attempts to 'lint' the content of `templates/` prior to the Github pages build, leading to false-positive errors. 
Ex: `The variable {{resolve:ssm:/${AOCStackPrefix} on line 159 in templates/amis/create-amis.yaml was not properly closed with }}.`
https://github.com/aws-quickstart/quickstart-aem-opencloud/runs/1188314982
This PR removes `templates` from the directory tree just prior to pushing to the `gh-pages` branch, allowing dynamic content, but preventing said issues.

Removing templates from gh-pages branch

---

.utils/commit_and_push_to_ghpages.sh

#69 introduced a bug where builds in github actions will fail with the error:
```
Run ./docs/boilerplate/.utils/commit_and_push_to_ghpages.sh
error: the following files have changes staged in the index:
templates/<template-name>
...
(use --cached to keep the file, or -f to force removal)
Error: Process completed with exit code 1.
```
This addresses the issue.
tested [here](https://github.com/jaymccon/quickstart-amazon-eks/runs/1189265513?check_suite_focus=true)

must force because files are already staged in the index

---

index-docinfo-footer.html
index.adoc

*Issue #, if available:* #71
Footer text is able to resolve adoc attributes (variables) but cannot process complex directives like `ifdef::`. So for quick start's that do not have a partner, and as such don't have `partner-company-name` defined, end up with a footer that contains the variable name instead:
```
© 2020, Amazon Web Services, Inc. or its affiliates and {partner-company-name}. All rights reserved.
```
this fixes that by rendering a `partner-company-footer` attribute tht conditionally is either blank or contains the needed part of the footer text.
cc: @sshvans for visibility

only add partner name to footer if defined

---

.utils/commit_and_push_to_ghpages.sh

Builds that contain no docs changes are failing currently. See https://github.com/aws-quickstart/quickstart-eks-snyk/runs/1222946875?check_suite_focus=true 
```
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
This fixes that by skipping commit if `git status` response contains `nothing to commit, working tree clean`.
Closes #2

only push if there are commits to push

---

.utils/commit_and_push_to_ghpages.sh

Logic in previous pr was faulty. The git status output for a clean tree, with commits that need to be pushed will include the string `nothing to commit, working tree clean`. Instead we should look for the part that tells whether we're up to date with the remote.

fix faulty push logic

---

.specific/_settings.adoc
.specific/deploy_steps.adoc

Added :parameters_as_appendix:
Addresses part of *[Issue #48](https://github.com/aws-quickstart/quickstart-documentation-base-common/issues/48) by moving parameter tables into an appendix.*

Moved parameter tables to an appendix & added a cross-ref

---

.utils/generate_metadata_attributes.py
.utils/generate_parameter_tables.py
.utils/requirements.txt

cfn-lint v 0.39.0 introduced a breaking change in the cfnlint.decode.decode method. This PR modifies our dynamic content generation scripts to reflect this change. Tested against a QS, both valid and non-valid template codepaths.

Updating cfn-lint behavior, version

---

_layout_cfn.adoc
deployment_steps.adoc

*Issue #, if available:* Fixes #66 
*Description of changes:* Moves note about QSS3 params to the parameter appendix, if `parameter_as_appendix` is enabled.

note should go with parameter tables

---

.utils/build_docs.sh
.utils/create_repo_structure.sh
_layout_cfn.lang.adoc
index.lang.adoc
planning_deployment.lang.adoc

*Description of changes: Added the required scripts and files to generate a second link for a second language. Translation and upkeep at this point are manual. But it is a way to maintain the second language in GIT. 

Adding support for a Second Language doc and link

---

.utils/generate_dynamic_content.sh
_layout_cfn.adoc
_layout_cfn.lang.adoc
deployment_steps.adoc

This PR adds the `no_parameters` attribute, configurable via `_settings.adoc` in `partner_editable`. There are edge cases where parameter generation is not desired. This attribute will skip inclusion in the HTML guides, and skip generation by our utility scripts.
FUnctionality has been tested locally.

New Attribute: no_parameters

---

.utils/commit_and_push_to_ghpages.sh

PR #101 introduced a bug in the Github Actions components. Github Actions uses `-u` in bash, which bails if a variable is not defined. 
This PR adds a default variable for the DOCBUILD_PROD env var in the script that pushes content to the `gh-pages` branch.

Adding default value for var introspected in Github Actions

---

_layout_cfn_eks_module.adoc
deployment_steps_eks_module.adoc
index.adoc
planning_deployment_eks_module.adoc

Up until now, eks addins (like [Snyk controller for Amazon EKS](https://aws-quickstart.github.io/quickstart-eks-snyk/)) have had their boilerplate based off a dedicated branch (`eks`) of this repo. This results in extra work keeping the `eks` branch up to date with changes to `main`.
This pr allows eks addin quickstarts to consume main branch of this repo. Setting `:eks_addin:` in `docs/partner_editable/_settings.adoc` identifies a repo as an eks addin. Existing eks addins need only change their submodule branch and do an update.
This is achieved by having a dedicated layout file, that points to dedicated boilerplate files where required, while trying to keep as much of the standard boilerplate where possible. 
By submitting this pull request, I confirm that you can use, modify, copy, and …

add support for eks addin quick starts

---

.utils/build_docs.sh

Currently if `images/` exists, the current command will move images from `docs/images` into `images/images`.
This PR swaps out `mv` for `rsync` so that content from `docs/images` is placed in `images`, regardless if it exists or not.
Note: Existing files will be overridden in `images` for the purposes of doc builds, but otherwise be left alone, as current automation leaves content in `gh-pages`.

Swapping out mv for rsync

---

planning_deployment.adoc
planning_deployment.lang.adoc

In both `planning_deployment` files, rephrased the lead-in under "Technical requirements" to eliminate the reference to "the following table" since we no longer use a table format for that information.

Updated "Technical requirements" lead-in in two files

---

.utils/docs_built_in_codebuild.sh

I had a nice awesome explaination but it didn't take, so..
TLDR:
- The current mechanism for identifying the submodule commit id for `docs/boilerplate` assumes the submodule has _not_ been initialized. That's now a false assumption. This PR leverages awk to catch both use cases
```
❯ git submodule
-0ed73f22f2ea225fb62a8e20369423c77d41ba57 docs/boilerplate
❯ git submodule | grep docs/boilerplate | cut -d - -f 2 | awk '{print $1}'
0ed73f22f2ea225fb62a8e20369423c77d41ba57
```
```
❯ git submodule
0ed73f22f2ea225fb62a8e20369423c77d41ba57 docs/boilerplate (heads/main)
❯ git submodule | grep docs/boilerplate | cut -d - -f 2 | awk '{print $1}'
0ed73f22f2ea225fb62a8e20369423c77d41ba57
```
```
❯ git submodule
0ed73f22f2ea225fb62a8e20369423c77d41ba57 docs/boilerplate (heads/main)
❯ git submodule | …
```

Awk to capture both variants of the commit ID

---

.utils/docs_built_in_codebuild.sh

Different git versions output submodule status in different ways. the version embedded into our containerized build process uses a `-` or `+` to denote submodule status. this PR trims both chars from the front of the commit ID, so the commit ID can be checked out successfully.

Tweaking doc_commit_id to reflect differnet output

---

.utils/generate_metadata_attributes.py
planning_deployment.adoc
planning_deployment.lang.adoc

Our condition around EC2 key relies on the `template_ec2` attribute, not `template_ec2_instances`; However, several resource types result in an EC2 instance. This PR modifies our generation to enable deterministic conditions. I've also modified references of `template_ec2` to `template_deterministic_ec2_instances` to reflect accordingly. 
Ran through the paces on one of my projects.

Adding deterministic logic to metadata attributs

---

deployment_steps.adoc

Just a small tweak to how `:no_parameters:` is evaluated in _deployment_steps.adoc_. A sentence got left behind.

Tweaking no_parameters conditional logic in deployment_steps

---

.utils/generate_parameter_tables.py

A mechanism to opt-out of the enforced template naming standards. 
To use:
`touch templates/.filename_standard_exception.txt`
In the file
- a list of filenames, relative to the `templates/` directory.

Adding: Mechanism to opt-out of template naming standards

---

.utils/generate_dynamic_content.sh

looks for :cdk_qs: in _settings.adoc, and then skips 'generate_metadata_attributes.py'

Adding checks for CDK to skip metadata generation

---

deployment_steps.adoc
deployment_steps_eks_module.adoc

In two deployment_steps docs, I bumped `:xrefstyle: short` to the top so that figure cross references generate "as shown in Figure x" instead of citing the whole figure caption.

Updated deployment_steps docs

---

.utils/docs_built_in_codebuild.sh

In non-CFN based projects, the `templates/` directory needs to be stubbed out (for now) to allow docs to be built. We'll fix this later, but we do need logic to exit if the `index.html` file wasn't generated properly. (silent error)

Exit if index.html hasn't been generated

---

.specific/deploy_steps.adoc
deployment_steps.adoc

In `deployment_steps.adoc`, I removed `[start=5]`, which has been forcing the numbering of Step 5, and replaced the blank lines preceding this step with `+`. These changes enable autonumbering to continue from the previous doc (`deploy_steps.adoc`, from which I removed the blank line at the end to support the cross-doc autonumbering). 
Result: In most cases, Step 5 will remain Step 5. For edge cases where this needs to be Step 6 or some other number, renumbering will happen automatically without authors having to tweak the files.

Enabled cross-doc autonumbering for deployment steps

---

.specific/_settings.adoc

Added the following to the settings file for CDK deployments:
// Uncomment the following two attributes if you are deploying a CDK Quick Start. Make sure to comment out :parameters_as_appendix: also.
// :cdk_qs:
// :no_parameters:

Added comments into Settings file for CDK deployment

---

.css/quickstart.css

- Responsive TOC & logo based on screen size.
- Removed pesky light blue border below logo.
- Navigation removal for smaller screens/window sizes (this was impacting mobile device views).
- Removal of yellow shading on 'info' icon, and change to green from black.
*Update: correcting logo path as i inadvertently changed it on an initial commit.

CSS responsive updates

---

.utils/generate_dynamic_content.sh

Document parameter tables build failing because path to write files to does not exist.
Ensure the folder `docs/generated/parameters/` exists.

Ensure the folder docs/generated/parameters/ exists

---

.utils/generate_dynamic_content.sh

Add missing directories causing doc builds to fail:
`docs/generated/services/`
`docs/generated/parameters/`
`docs/generated/regions/`

Add missing directories causing doc builds to fail

---

planning_deployment.adoc
planning_deployment.lang.adoc

Per AWS guideline to say "AWS Regions" on first mention.

Added "AWS" before "Regions" in the subhead

---

.specific/deploy_steps.adoc

Fixed a broken cross-ref to the "Supported AWS Regions" section earlier in the guide.

Fixed a broken cross-ref in deploy_steps.adoc

---

planning_deployment.adoc
planning_deployment.lang.adoc

The "Deployment options" section has been in the wrong place. This became evident in docs with lots of steps in **pre-reqs.adoc**. With this change, "Deployment options" precedes the preparation steps instead of being presented as a subsection of them.

Moved "Deployment options" section to where it belongs

---

.specific/_settings.adoc
_layout_cfn.adoc
_layout_cfn.lang.adoc
introduction.adoc

Adding a new parameter to check if the repo is private for whatever the reason (ex: SaaS workloads, Strategic engagements) and then hiding github related links in the generated guide.

Adding support for private repos

---

.utils/generate_parameter_tables.py

created a private method to fix the formatting issue.
previous fix had issue with blank values and requires input which needed to be bold. 
this PR fixes that.

fix for asterisk and pipe in parameter default and description

---

.utils/build_docs.sh

Doc builds in IA appear as preview. This enables them to be production builds

Adding in aws-ia to list of repo owners
